### ISSUE TITLE
Chat on small screens

### ISSUE THREAD

**Issue by RafailStratiotis** [opensource-socialnetwork/opensource-socialnetwork#1680] opened 2020-03-19 17:30 UTC
on small screens where the conversation is at the bottom, when I click on the person I want to start a conversation with, the tab don't open

**Comment by RafailStratiotis** [comment] 2020-03-19 18:07
i found the problem,
the problem is
```
<div class="ossn-chat-base hidden-xs hidden-sm" style="
height:275px ;
width:33px ;
```
the numbers are too small and so the tab does not appear...

**Comment by RafailStratiotis** [comment] 2020-03-20 07:57
the problem is fixed by placing the following code in
/components/OssnChat/plugins/default/css/OssnChat.php

and place on  (.ossn-chat-base )
the code (width: -webkit-fill-available;)

**Comment by lianglee** [comment] 2020-03-20 07:58
Will -webkit-fill-available works on firefox too?

**Comment by RafailStratiotis** [comment] 2020-03-20 08:08
no :/ for firefox we need (width: -moz-available;) code
do you have any idea how we can do it for all browsers ?
and on the Edge it doesn't work :/

**Comment by RafailStratiotis** [comment] 2020-03-20 08:43
okey with  `width: 100%;` the code is working

**Comment by githubertus** [comment] 2020-03-21 15:50
Hi Rafail,
could you please tell in pixels (width x height) what you meant with 'small screen'?

**Comment by RafailStratiotis** [comment] 2020-03-21 15:58
Hello Z-Man !

let's say on a 14-inch laptop screen with 150% scale and layout

**Comment by githubertus** [comment] 2020-03-21 16:37
first of all I can't reproduce your dimension of ossn-chat-base
both on Goblue and GreenByGreen I'm getting:
height: 33 px ;
width: 850px ;
next you have to be aware that your unusual scaling to 150% is triggering 
@media (max-width: 991px) and (min-width: 768px)
.hidden-sm {
    display: none !important;
}
that's the reason the tab is no more visible
(at least that's what happening on my site)

so next question: which theme are you running?

**Comment by RafailStratiotis** [comment] 2020-03-21 16:53
the problem has been resolved with the code i added to .ossn-chat-base.
the theme we use is "social" I do not know if the problem also exists in other themes.

i know it activates @media (max-width: 991px) and (min-width: 768px)
but my laptop itself is set to 150%
because it has a small screen at 100% the icons and fonts look very small
so one visitor could have the same problem in the future

**Comment by githubertus** [comment] 2020-03-21 17:11
hmm sorry, but can't reproduce that here
as I said on my laptop scaling to 150% gives display: none
so of course it makes no difference whatever width is set.
aside from that running with 100% (as most users would do) and 100% is drifting my tabs out of the right, so this can't be a general solution.

**Comment by RafailStratiotis** [comment] 2020-03-21 17:23
I can't understand exactly the problem you're saying
however I've been changing the code for some time now..
Take a look

`.ossn-chat-base {`
`    border-bottom: 0;`
`    bottom: 0;`
`    left: auto;`
`    display: block;`
`    font-family: "Lucida Grande",Verdana,Arial,"Bitstream Vera Sans",sans-serif;`
`    font-size: 11px;`
`    height: 33px;`
`    position: fixed !important;`
`    text-align: left;`
`    z-index: 1028;`
`    margin-top: 8px;`
`    right: 5px;`
`    color: #000;`
`    max-width: initial !important;`
`    float: right;`
`    width: 100%;`

**Comment by lianglee** [comment] 2020-07-15 20:38
I believe you mean the width : ossn-chat-base 
It can not be set to 100% either as if user have a large display and the chat will move under the list appear on right side. 
I am closing this issue so we can prepare 5.3 if someone reports issue again we'll investigate in deep.

![image](https://user-images.githubusercontent.com/805066/87593449-e7bde580-c704-11ea-803a-e6e4d457123b.png)

**Closed by lianglee** 2020-07-15 20:38 UTC
