### ISSUE TITLE
long comments are under the camera icon

### ISSUE THREAD

**Issue by seimei** [opensource-socialnetwork/opensource-socialnetwork#165] opened 2015-01-04 18:28 UTC
If you write long comments, the last letters are under the camera icon.

**Comment by lianglee** [comment] 2015-01-04 19:34
Duplicate of #164 (fixed in v2.0-dev)

**Closed by lianglee** 2015-01-04 19:34 UTC

**Comment by seimei** [comment] 2015-01-04 19:44
it's not a duplicate, it the opposite of #164, 
![ossn](https://cloud.githubusercontent.com/assets/10389633/5607230/6957807e-9452-11e4-9d2e-355ec8bac746.png)

**Comment by githubertus** [comment] 2015-01-04 19:48
The text is scrolling, yes. But at least you can read what you're typing, now :)

**Comment by seimei** [comment] 2015-01-04 19:53
exactly, but i think it will be fixed in the next time :b :santa:

**Comment by githubertus** [comment] 2015-01-04 23:45
Seimei is right:
I just installed the fix. It's different than my zfix #164:
No more overwriting. Okay.
But the field width is still  too wide hiding the last characters. Please check again

**Comment by seimei** [comment] 2015-01-04 23:52
That's what I mean. Thanks githubertus

**Comment by lianglee** [comment] 2015-01-05 11:50
Yes need to shrink width of input field
