### ISSUE TITLE
OSSN Wall in v3.0-development

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#446] opened 2015-06-25 14:28 UTC
It isn't really possible to make a posting. The only thing which someone gets is a small alert in the left top. You really don't know why doesn't go it.
![unbenannt1](https://cloud.githubusercontent.com/assets/5566418/8356345/ff80ea98-1b54-11e5-96a2-dfa78b4d5286.JPG)
The only thing what will posting is if you upload a profile pic.
------------------------------
In the Wall on your own profile you see posts from other people if you're not friendly with them. My settings are 'Friends post only' for the Wall. The difference to version 2 is also that you see posts from friends in your own Wall.

**Comment by lianglee** [comment] 2015-06-27 06:29
Duplicate of : #448

**Closed by lianglee** 2015-06-27 06:29 UTC
Labels: duplicate
