### ISSUE TITLE
[OSSN 3.0-dev] basic_settings

### ISSUE THREAD

**Issue by ctlui** [opensource-socialnetwork/opensource-socialnetwork#452] opened 2015-07-01 14:00 UTC
In administrator when you go to "site settings -> Basic" the page is missing, just got the title.
I think we should have /system/default/forms/admin/basic_settings.php

**Comment by lianglee** [comment] 2015-07-01 19:27
Thanks for report

**Comment by moneya** [comment] 2015-07-03 20:08
@ctlui  thanks for the report

hi @lianglee  since this is sorted out please close the issue.

**Comment by lianglee** [comment] 2015-07-04 08:43
@moneya no, the issue is still there i think, i know the fix, i'll fix during weekend.

**Comment by lianglee** [comment] 2015-07-04 21:25
fixed

**Closed by lianglee** 2015-07-04 21:25 UTC
