### ISSUE TITLE
[B] Admins can not view "friends only" posts if not friend with user

### ISSUE THREAD

**Issue by queermeet-dev** [opensource-socialnetwork/opensource-socialnetwork#2403] opened 2024-10-17 12:07 UTC
When someone publish a post with privacy "only friends" and I am as an admin commenting the post and someone reacts to my comment and I click on the notification, I get the error "The page you requested is unavailable or may have been deleted"

Same happens when I try to open the post by clicking on it on the wall:

https://github.com/user-attachments/assets/010ddea9-457b-46a0-91b9-e10814b02ba0

**Comment by githubertus** [comment] 2024-10-20 11:13
Can't reproduce on Ossn 7.6 Free
![issue-2403-1](https://github.com/user-attachments/assets/61b19bec-8eb1-4ef6-a9c5-ef464110ae58)

The activity-item of this example post is 450
and I (the admin) can visit MYURL/post/view/450 without problem as the owner (Botox) of the post can do

What about your site: Is the post's owner able to see YOURURL/post/view/YOURACTIVITY_ITEM_ID 
but the admin gets an error with the same page?

**Comment by queermeet-dev** [comment] 2024-10-20 11:23
I tried this on a complete new installation of OSSN 7.6

When the post owner opens MYURL.de/clean/post/view/11 it is working, when the site admin opens MYURL.de/clean/post/view/11 i get the error


<img width="1440" alt="Bildschirmfoto 2024-10-20 um 13 22 13" src="https://github.com/user-attachments/assets/79b06fb1-0848-44d8-bfe6-2baf62f363b7">

**Comment by lianglee** [comment] 2024-10-20 11:37
Did you tried on free version? Because it looks different version then
free. Notice no powered by and that blue tick.

**Comment by lianglee** [comment] 2024-10-20 12:02
You know the drill disable component one by one and see which premium
component causing issue

**Comment by queermeet-dev** [comment] 2024-10-20 12:56
I can also reproduce it on free version

That is the post:

<img width="1440" alt="Bildschirmfoto 2024-10-20 um 14 54 48" src="https://github.com/user-attachments/assets/3f4b52b8-78d9-4a21-8503-c95e5ea62640">



That is the view from post owner 

<img width="1440" alt="Bildschirmfoto 2024-10-20 um 14 55 22" src="https://github.com/user-attachments/assets/75a29e07-e670-4dd8-956b-4445623c756b">



That is from admin:

<img width="1440" alt="Bildschirmfoto 2024-10-20 um 14 54 21" src="https://github.com/user-attachments/assets/9177b804-dd8b-4c98-b63f-e18005266f48">



Important is, that the privacy of the post is the to "friends"

**Comment by githubertus** [comment] 2024-10-20 13:12
Ahhh got it!
On my first attempt Botox and admin were friends.
Now, that I quit friendship with Botox, I'm running into the same issue as queermeet-dev.
Needs investigation.

**Comment by lianglee** [comment] 2024-10-20 13:22
Closing as fixed thanks for sharing.

**Closed by lianglee** 2024-10-20 13:22 UTC

**Comment by queermeet-dev** [comment] 2024-10-20 13:23
You already fixed it? Which files/component do I have to update to fix this?

**Comment by lianglee** [comment] 2024-10-20 13:28
See above ...added a commit that referenced this issue....
