### ISSUE TITLE
Mark all notifications as read

### ISSUE THREAD

**Issue by PrashantRe** [opensource-socialnetwork/opensource-socialnetwork#375] opened 2015-02-19 11:05 UTC
Mark all notifications as read.
need same option which is provided here on github.

**Comment by githubertus** [comment] 2015-02-19 11:46
This has been addressed with #202 already. Please, take yourself a little time and step through open issues first before opening a "new" one.

**Comment by lianglee** [comment] 2015-02-19 12:41
Duplicate of #202

**Closed by lianglee** 2015-02-19 12:41 UTC
Labels: duplicate
