### ISSUE TITLE
Default SMTP Mail and Personal Background

### ISSUE THREAD

**Issue by Phineasx** [opensource-socialnetwork/opensource-socialnetwork#1016] opened 2017-01-18 13:49 UTC
1- I would like to change default e-mail in to **SMTP**. How can i do this?

2-  I would like to change the **background** image for user **homepage and other pages**. How can i do this?

Thanks for helping.

**Comment by lianglee** [comment] 2017-01-18 20:19
Please see the community website for help,  there is already many topics exists,  you can create a new topics for seeking help.

The SMTP component exists  https://github.com/opensource-socialnetwork/SMTP

Closing due to its not a bug report, use community for help.

**Closed by lianglee** 2017-01-18 20:19 UTC
